apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: apimysqlrodrigomoro-hpa
  namespace: apimysqlapplication
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apimysqlrodrigomoro
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
