apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-mysqlapirodrigomoro
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysqlapirodrigomoro
  namespace: apimysqlapplication
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-class-mysqlapirodrigomoro
  hostPath:
    path: /mnt/data/mysql

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysqlapirodrigomoro
  namespace: apimysqlapplication
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: storage-class-mysqlapirodrigomoro

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-application-deployment
  namespace: apimysqlapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-application
  template:
    metadata:
      labels:
        app: mysql-application
    spec:
      containers:
        - name: mysql-application-container
          image: docker.io/rodrigomoro/mysqlapirodrigomoro:v13
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets-appuser-mysqlapirodrigomoro
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets-appuser-mysqlapirodrigomoro
                  key: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets-root-mysqlapirodrigomoro
                  key: mysql-root-password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m" # 250 millicpu, or 0.25 cpu cores
            limits:
              memory: "1Gi"
              cpu: "500m" # 500 millicpu, or 0.5 cpu cores
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: pvc-mysqlapirodrigomoro

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: apimysqlapplication
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-application
  type: ClusterIP
